#!/bin/bash

if [ -z "$GITHUB_ACTIONS" ]; then
    rm -rf venv
    python3.7 -m virtualenv venv
    PIP="./venv/bin/pip"
else
    PIP=pip
fi

"$PIP" install --no-cache-dir -e .
# Testing
"$PIP" install --no-cache-dir pytest pytest-cov pytest-asyncio hypothesis httpx
# Static analysis (without changing files)
"$PIP" install --no-cache-dir mypy flake8 flake8-bugbear flake8-pie pep8-naming
# Linting (with changing files)
"$PIP" install --no-cache-dir black autoflake isort
# Security checks and other metrics
"$PIP" install --no-cache-dir bandit radon safety
# Documentation
"$PIP" install --no-cache-dir mkdocs mkdocs-material mkautodoc
# Packaging
"$PIP" install --no-cache-dir twine wheel
