#!/bin/bash

rm -rf venv
python3.7 -m virtualenv venv

./venv/bin/pip install --no-cache-dir -e .

# Testing
./venv/bin/pip install --no-cache-dir pytest pytest-cov pytest-asyncio \
    hypothesis httpx
# Static analysis (without changing files)
./venv/bin/pip install --no-cache-dir mypy flake8 flake8-bugbear flake8-pie pep8-naming
# Linting (with changing files)
./venv/bin/pip install --no-cache-dir black autoflake isort
# Security checks and other metrics
./venv/bin/pip install --no-cache-dir bandit radon safety
# Documentation
./venv/bin/pip install --no-cache-dir mkdocs mkdocs-material mkautodoc
# Packaging
./venv/bin/pip install --no-cache-dir twine wheel
