#!/bin/bash

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="./venv/bin/"
fi

set -e

echo -e "\033[0;32mRemoving Unused Imports (autoflake):\033[0m"
echo
${PREFIX}autoflake --in-place --recursive melodiam tests setup.py
echo "----------"

echo -e "\033[0;32mSorting Imports (isort):\033[0m"
echo
${PREFIX}isort --project=melodiam melodiam tests setup.py
echo "----------"

echo -e "\033[0;32mLinting (black):\033[0m"
echo
${PREFIX}black --target-version=py37 melodiam tests setup.py
echo "----------"
