#!/bin/bash

sudo docker run -p ${1:-127.0.0.1}:${2:-5432}:5432 \
    --name melodiam-db -d melodiam-db:latest

echo "Waiting for database to initialize..."
until sudo docker exec melodiam-db pg_isready >/dev/null ; do sleep 0.5 ; done
