#!/bin/bash

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="./venv/bin/"
fi

set -x

echo -e "\033[0;32mCode Security Checks (bandit):\033[0m"
echo
# B322 error is specific to Python 2, so we ignore it for now
# See: https://github.com/PyCQA/bandit/issues/402
${PREFIX}bandit --quiet --skip=B322 -r melodiam
echo "----------"

echo -e "\033[0;32mDependencies Security Checks (safety):\033[0m"
echo
${PREFIX}safety check --full-report
echo "----------"
